node('agent-1'){

    stage("checkout the application code"){
        if(env.branch != "main"){
            git clone https://app.git
        }
    }
    stage("unit test & sonar report generation"){
        if(env.branch != "main"){
            sh "mvn test --properties && sonar run"
            sh "send a mail of this report to approvers && "
        }
    }
    stage("build docker build"){
        docker {

        }

        1.0.0
    }
    stage("deployment to dev cluster"){
        dev = training cluster
    }
}